<?php
include 'handleAssetMessages.php'
?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Deprovision Assets | SnipeTools</title>
	<link rel = "stylesheet" href = "../styles/deprovisionStyle.css">
</head>
<body>
	<?php echo $audioMessage; ?>
	<div id = "page">
		<h1>Deprovision Assets</h1>

		<form action="../api_requests/deprovisionAPI.php" method="GET" autocomplete="on">
			<label for="serial">Scan Serial #</label>
			<input type="hidden" name="source" value="deprovision">
			<input type="text" id="serial" name="serial" autofocus required autocomplete="off">
			<button type="submit">Submit</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
			<br>
			<input type="checkbox" id="GAdmin" name="GAdmin" value="on" <?php echo (isset($_GET['GoogleRequestStatus']) ? 'checked' : ''); ?>>
			<label> Deprovision this Asset in Google Admin (recommended, only for Chromebooks)</label>
			<br>
		</form>

		<h2><?php echo $assetMessage1; ?></h2> <!-- Generated by handleAssetMessages.php -->
		<h3><?php echo $assetMessage2; ?></h2> <!-- Generated by handleAssetMessages.php -->
		<h3><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
		<button data-url ="../index.php">Return Home</button>
		<script src = "../scripts/buttons.js"></script>
	</div>


</body>
</html>