<?php
include 'handleAssetMessages.php'
?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Return Assets to Office | SnipeTools</title>
</head>
<body>
	<?php echo $audioMessage; ?>
	<div style="margin: 0; position: absolute; top: 40%; left: 50%; -ms-transform: translate(-50%, -50%); transform: translate(-50%, -50%); text-align: center;">
	<h1>Return Assets to Office</h1>

	<form action="../api_requests/officeAPI.php" method="GET" autocomplete="on">
		<label for="serial">Scan Serial #</label>
		<input type="hidden" name="source" value="office">
		<input type="text" id="serial" name="serial" autofocus required autocomplete="off">
		<button type="submit">Submit</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
		<br>
		<input type="checkbox" id="GAdmin" name="GAdmin" value="on" <?php echo (isset($_GET['GoogleRequestStatus']) ? 'checked' : ''); ?>>
		<label> Make sure this asset is provisioned in Google Admin (optional, only for Chromebooks)</label>
		<br>
	</form>

	<h2><?php echo $assetMessage1; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetMessage2; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
	<button id = "return" data-url ="../index.php">Return Home</button>
	<script src = "../scripts/buttons.js"></script>
	</div>
</body>
</html>