<?php
include 'handleAssetMessages.php'
?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Return Assets to Office</title>
</head>
<body>
	<h1 style:'text-align:center;'>Return Assets to Office</h1>

	<form style:'text-align:center;' action="../api_requests/getIDBySerial.php" method="GET" autocomplete="off">
		<label for="serial">Scan Serial #</label>
		<input type="hidden" name="source" value="office">
		<input type="text" id="serial" name="serial" autofocus required>
		<button type="submit">Submit (not needed?)</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
	</form>

	<h2 style:'text-align:center;'><?php echo $assetMessage; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3 style:'text-align:center;'><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
	<a style:'text-align:center;' href="../index.html">Return Home</a>
</body>
</html>