<?php
include 'handleAssetMessages.php'

//determine which options should be autoselected upon page refresh
//This all comes from my stubbornnesss to not use JavaScript


?>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Validate Assets | SnipeTools</title>
</head>
<body>
	<?php echo $audioMessage; ?>
	<div style="margin: 0; position: absolute; top: 40%; left: 50%; -ms-transform: translate(-50%, -50%); transform: translate(-50%, -50%); text-align: center;">
	<h1>Validate Assets</h1>

	<form action="../api_requests/validateAPI.php" method="GET" autocomplete="on">
		<label for="serial">Scan Serial #</label>
		<input type="hidden" name="source" value="validate">
		<input type="text" id="serial" name="serial" autofocus required autocomplete="off">
		<button type="submit">Submit</button> <!-- Submit button is here for convenience if manually typing in serial, pressing enter works fine-->
		<br><br>

		<label>Asset Status: </label>
		<select name="status" id="location" required>
			<option>Ready to Deploy</option>
			<option>Deployed</option>
			<option>Deprovisioned</option>
			<option>Leave as is</option>
		</select>
		<br>
		
		<label>Asset Location: </label>
		<select name="location" id="location" required>
			<option>Dayton</option>
			<option>Elderton Elementary</option>
			<option>Shannock Valley</option>
			<option>West Hills Primary</option>
			<option>West Hills Intermediate</option>
			<option>Armstrong High School</option>
			<option>West Shamokin High School</option>
			<option>Admin</option>
			<option>Office</option>
			<option>Elderton High School (Storage)</option>
			<option>Leave as is</option>
		</select>
		<br>

		<input type="checkbox" id="remName" name="remName" value="on">
		<label> Remove Asset Name</label>
		<br>
		
		<input type="checkbox" id="retag" name="retag" value="on">
		<label> Set Asset Tag equal to Serial Number</label>
		<br>
		
		<input type="checkbox" id="checkin" name="checkin" value="on">
		<label> Check the Asset in from any Users</label>
		<br>
		
		
		<input type="checkbox" id="GAdmin" name="GAdmin" value="on" <?php echo (isset($_GET['GoogleRequestStatus']) ? 'checked' : ''); ?>>
		<label> Make sure this asset is provisioned in Google Admin (optional, only for Chromebooks)</label>
		<br>
	</form>

	<h2><?php echo $assetMessage1; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetMessage2; ?></h2> <!-- Generated by handleAssetMessages.php -->
	<h3><?php echo $assetLink; ?></h3> <!-- Generated by handleAssetMessages.php-->
	<a href="../index.html">Return Home</a>
	</div>
</body>
</html>